export type Languages = {
  language: string
  ename: string
  code: string
}

export const LanguagesList: Languages[] = [
  { language: 'English', code: 'en', ename: 'English' },
  { language: '中文(简体)', code: 'zh-CN', ename: 'Chinese (Simplified)' },
  { language: '中文(繁體)', code: 'zh-TW', ename: 'Chinese (Traditional)' },
  { language: 'Español', code: 'es', ename: 'Spanish' },
  { language: 'Français', code: 'fr', ename: 'French' },
  { language: '日本語', code: 'ja', ename: 'Japanese' },
  { language: 'Deutsch', code: 'de', ename: 'German' },
  { language: 'Português', code: 'pt', ename: 'Portuguese' },
  { language: 'العربية', code: 'ar', ename: 'Arabic' },
  { language: 'Русский', code: 'ru', ename: 'Russian' },
  { language: 'Italiano', code: 'it', ename: 'Italian' },
  { language: '한국어', code: 'ko', ename: 'Korean' },
  { language: 'हिन्दी', code: 'hi', ename: 'Hindi' },
  { language: 'Nederlands', code: 'nl', ename: 'Dutch' },
  { language: 'Polski', code: 'pl', ename: 'Polish' },
  { language: 'አማርኛ', code: 'am', ename: 'Amharic' },
  { language: 'Български', code: 'bg', ename: 'Bulgarian' },
  { language: 'বাংলা', code: 'bn', ename: 'Bengali' },
  { language: 'Català', code: 'ca', ename: 'Catalan' },
  { language: 'Čeština', code: 'cs', ename: 'Czech' },
  { language: 'Dansk', code: 'da', ename: 'Danish' },
  { language: 'Ελληνικά', code: 'el', ename: 'Greek' },
  { language: 'Eesti', code: 'et', ename: 'Estonian' },
  { language: 'فارسی', code: 'fa', ename: 'Persian' },
  { language: 'Suomi', code: 'fi', ename: 'Finnish' },
  { language: 'Filipino', code: 'fil', ename: 'Filipino' },
  { language: 'ગુજરાતી', code: 'gu', ename: 'Gujarati' },
  { language: 'עברית', code: 'he', ename: 'Hebrew' },
  { language: 'Hrvatski', code: 'hr', ename: 'Croatian' },
  { language: 'Magyar', code: 'hu', ename: 'Hungarian' },
  { language: 'Bahasa Indonesia', code: 'id', ename: 'Indonesian' },
  { language: 'ಕನ್ನಡ', code: 'kn', ename: 'Kannada' },
  { language: 'Lietuvių', code: 'lt', ename: 'Lithuanian' },
  { language: 'Latviešu', code: 'lv', ename: 'Latvian' },
  { language: 'മലയാളം', code: 'ml', ename: 'Malayalam' },
  { language: 'मराठी', code: 'mr', ename: 'Marathi' },
  { language: 'Bahasa Melayu', code: 'ms', ename: 'Malay' },
  { language: 'Norsk', code: 'no', ename: 'Norwegian' },
  { language: 'Română', code: 'ro', ename: 'Romanian' },
  { language: 'Slovenčina', code: 'sk', ename: 'Slovak' },
  { language: 'Slovenščina', code: 'sl', ename: 'Slovenian' },
  { language: 'Српски', code: 'sr', ename: 'Serbian' },
  { language: 'Svenska', code: 'sv', ename: 'Swedish' },
  { language: 'Kiswahili', code: 'sw', ename: 'Swahili' },
  { language: 'தமிழ்', code: 'ta', ename: 'Tamil' },
  { language: 'తెలుగు', code: 'te', ename: 'Telugu' },
  { language: 'ไทย', code: 'th', ename: 'Thai' },
  { language: 'Türkçe', code: 'tr', ename: 'Turkish' },
  { language: 'Українська', code: 'uk', ename: 'Ukrainian' },
  { language: 'اردو', code: 'ur', ename: 'Urdu' },
  { language: 'Tiếng Việt', code: 'vi', ename: 'Vietnamese' },
]
